# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.5"
manifest_format = "2.0"
project_hash = "64f446b896f6bf1ad110155c945e831d8a7849c8"

[[deps.EventNotifiers]]
git-tree-sha1 = "e97e476f17d72f154bf4a1867c386dfac8c0bd7e"
uuid = "de92ec2b-fb1f-40f8-8e84-3094df8dc533"
version = "1.0.1"

[[deps.GDMathLib]]
git-tree-sha1 = "e897ee77b49945ceee40cc8441ed123a4ce5961a"
uuid = "ed54f85f-91e8-4912-9e4a-a43af611f8a9"
version = "1.3.0"

[[deps.NodeTree]]
git-tree-sha1 = "d9d5401eb270ef0513087c04b624bd589456288a"
uuid = "2904b71e-4df0-4a82-a724-4bbee9184de7"
version = "1.0.1"

[[deps.Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"
